# Generated by Django 3.2.10 on 2021-12-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
    ]
