import { library } from '@fortawesome/fontawesome-svg-core'
import { 
    fab, 
    faFacebookSquare,
    faGoogle, 
    } from '@fortawesome/free-brands-svg-icons'

import { 
    faCheckSquare, 
    faCoffee, 
    faPaperPlane, 
    faEnvelope,
    faCaretLeft,
    faKey,
    faUserAlt, 
    faTimesCircle,
    faTimes,
    faCamera,
    faInfoCircle,
    faEdit,
    faTrash,
    faStore,
    faCopyright,
    faThList,
    faCube,
    faImages,
    faCartPlus,
    faShoppingCart,
    faDollarSign,
    } from '@fortawesome/free-solid-svg-icons'

library.add(
    fab, 
    faCheckSquare, 
    faCoffee, 
    faPaperPlane,
    faEnvelope,
    faFacebookSquare,
    faGoogle,
    faCaretLeft ,
    faKey,
    faUserAlt,
    faTimesCircle,
    faTimes,
    faCamera,
    faInfoCircle,
    faEdit,
    faTrash,
    faThList,
    faCopyright,
    faCube,
    faStore,
    faImages,
    faCartPlus,
    faShoppingCart,
    faDollarSign,
    )